<a href="https://colab.research.google.com/github/sonjoy1s/ML/blob/main/Data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data analysis and Data Processing

NumPy

In [37]:
# Ndarray : N demensional array
import numpy as np
arr1 = np.array([1,2,3])
arr2 = arr1 * 5
print(arr2)

[ 5 10 15]


Ndarray

In [38]:
import numpy as np
arr1 = np.array([1, 2, 3, 4,5])
print(type(arr1))
print(arr1.ndim)

# 2D array
arr2 = np.array([[1, 2, 3], #row 1
                 [4, 5, 6] # row 2
                 ])
print(arr2.ndim)


# 3D array :- 3D array holo ekta array vitor onek ghula 2D array
arr3 = np.array([
    # 1st floor
    [[1,2,3],# row1
     [4,5,6] ], #row2
    # 2nd floor
    [[1,2,3],# row1
     [4,5,6] ]#row2

])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


Array Attributes

In [39]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


# datatype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)



# size
print(arr1.size)
print(arr2.size)
print(arr3.size)


1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


DataType

In [40]:
arr1 = np.array([1,2,3])
print(arr1.dtype)

arr2 = np.array([1.5 , 6.7, 7.0])
print(arr2.dtype)

arr3 = np.array([1, 6, 7.0])
print(arr3.dtype)

arr4 = np.array([1, 6.7, '3'])
print(arr4.dtype)

int64
float64
float64
<U32


In [41]:
# selection of datatype
import numpy as np
arr1 = np.array([1,2,3], dtype =np.int8)
print(arr1.dtype)
arr1 = arr1.astype(np.int16)
print(arr1.dtype)

int8
int16


ndarray creation from existing data :


In [42]:
# List
lst = [10,20,30,40.5]
arr = np.array(lst)
arr1 =arr.astype(np.int32)
print(arr)
print(type(arr))
print(arr1.dtype)


lst1 =[10, True, 'abc',19.5]
arr2 = np.array(lst1)
print(arr2)
print(arr2.dtype)




#matrix
matrix = np.array([[1, 2, 3], #row 1
                 [4, 5, 6] # row 2
                 ])
arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10.  20.  30.  40.5]
<class 'numpy.ndarray'>
int32
['10' 'True' 'abc' '19.5']
<U32
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [43]:
# tuple
tpl =(10,20,30)
arr = np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1


In [44]:
# Set
St ={10, 60, 50 ,70}
arr = np.array(St)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

{10, 60, 50, 70}
<class 'numpy.ndarray'>
object
()
0


In [45]:
# Set cover list *** list e covert kore nite hoy
St ={10, 60, 50 ,70}
arr = np.array(list(St))
arr = arr.astype(np.int32)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 60 50 70]
<class 'numpy.ndarray'>
int32
(4,)
1


In [46]:
# dictionary
dc = {'a':10, 'b':20, 'c':30}
#arr = np.array(dc)
#print(type(dc))
keys = dc.keys()
print(keys)
values = dc.values()
print(values)
items = dc.items()
print(items)

dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [47]:
# dictionary
dc = {'a':10, 'b':20, 'c':30}
#arr = np.array(dc)
#print(type(dc))
arr = np.array(list(keys))
print(arr)
keys = dc.keys()
print(keys)
print(arr.shape)
print(arr.dtype)
values = dc.values()
print(values)
items = dc.items()
print(items)
print(arr.size)

['a' 'b' 'c']
dict_keys(['a', 'b', 'c'])
(3,)
<U1
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
3


In [48]:
# values to ndarray
dc = {'a':10, 'b':20, 'c':30}
#arr = np.array(dc)
#print(type(dc))
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
values = dc.values()
print(values)
items = dc.items()
print(items)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
(3,)
int64
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
3


In [49]:
# Items to ndarray
dc = {'a':10, 'b':20, 'c':30}
#arr = np.array(dc)
#print(type(dc))
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(values)
print(arr.size)
print(keys)
print(arr.ndim)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
dict_values([10, 20, 30])
6
dict_keys(['a', 'b', 'c'])
2


In [50]:
# np.zeros

arr =np.zeros((2,3),dtype =np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
arr = np.zeros_like(arr3)
print(arr)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
[0. 0. 0.]
1
3


In [51]:
# np.ones

arr =np.ones((3,4,3),dtype =np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
arr = np.ones_like(arr3)
print(arr)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
[1. 1. 1.]
1
3


In [52]:
# np.empty

arr =np.empty((4,3),dtype =np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[1. 1. 1.]
(3,)


In [53]:
#np.full

arr =np.full((4,3),10)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr3,10.5)
print(arr)
print(arr.shape)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12
[10.5 10.5 10.5]
(3,)


In [54]:
arr = np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.9274467  0.39512645 0.62731093]
 [0.93282568 0.24405889 0.33646647]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [55]:
arr = np.random.randint(1,10,(2,3)) # randint dile data type int dekhabe
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[9 2 7]
 [3 7 4]]
<class 'numpy.ndarray'>
(2, 3)
2
6


In [56]:
arr = np.random.uniform(50,100,(3,4)) # uniform dile float dekhabe
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[89.38589133 57.78852883 77.22681614 86.18118286]
 [72.37118397 67.47159315 82.37746393 62.13865352]
 [61.35093018 97.79704203 72.60069424 75.62475027]]
<class 'numpy.ndarray'>
float64
(3, 4)
2
12


**bold text** Array with range function

In [57]:
# np.arange(frist, end, step)-> similer to range function
import numpy as np

arr = np.arange(1, 10, 1)
mat = arr.reshape(3,3)
print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [58]:
# np.linespace(start, end, koita)
import numpy as np
arr = np.linspace(1, 10, 10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
(10,)
1
10


In [59]:
#np.logspace
arr = np.logspace(0, 4, 6, base =2)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
float64
(6,)
1
6


In [60]:
# diogonal matrix
diagonal_matrix = np.diag([1,2,3])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)


In [61]:
# identity matrix


identity_matrix =np.eye(4)
print(identity_matrix)
print(identity_matrix.shape)

# np.eye(row,col)
mtx =np.eye(3,4,-1)
print(mtx)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [62]:
# indexing and slicing
print(arr1)
print(arr2)
print(arr1[2])
arr1[2] =100
print(arr1)

[10 20 30 40]
['10' 'True' 'abc' '19.5']
30
[ 10  20 100  40]


In [63]:
arr1_mod = arr1[1:4]
print(arr1_mod)

[ 20 100  40]


In [64]:
arr = np.array([1,2,3])
print(arr.ndim)

1


In [65]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [67]:
arr = np.full([[10,20,30],[40,50,60]])
arr =arr[:1]
print(arr)

TypeError: full() missing 1 required positional argument: 'fill_value'

In [69]:
arr = np.array([1,2,3,4,5])
arr[1:4] =0
print(arr)

[1 0 0 0 5]
