<a href="https://colab.research.google.com/github/sonjoy1s/ML/blob/main/MidExam_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###My Email ID : adittysonjoy@gmail.com

In [63]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# 1 NumPy

### #Ans to the Question no 1:

In [64]:

salery_ar = np.array(salaries)
print(salery_ar)
age_ar = np.array(ages)
print(age_ar)
#frist ei dtype, ndim,size er salary_part
print(salery_ar.dtype)
print(salery_ar.ndim)
print(salery_ar.size)

#2nd ei dtype, ndim,size er age_part
print(age_ar.dtype)
print(age_ar.ndim)
print(age_ar.size)

[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
[56 46 32 25 38 56 36 40 28 28]
int64
1
10
int64
1
10


# Ans to Q no 2 :

In [65]:


# salary part
high_sale = np.max(salery_ar)
print(high_sale)
low_sale =np.min(salery_ar)
print(low_sale)
#high_ag = np.max(age_ar)
#print(high_ag)

#avg part
avg_sal = np.mean(salery_ar)
print(avg_sal)
avg_age = np.mean(age_ar)
print(avg_age)


89735
30769
57446.9
38.5


# Ans to Q no 3:

In [66]:

#print(age_ar)

filter_ag = age_ar[age_ar>30]
print(filter_ag)

len_ag = len(filter_ag)
print(len_ag)

[56 46 32 38 56 36 40]
7


# Ans to Q no 4 :

In [67]:


#print(age_ar)
update_ag = age_ar+5
print(update_ag)

[61 51 37 30 43 61 41 45 33 33]


# Ans to Q no 5 :

In [68]:

All_em_sal = np.sum(salery_ar)
print(All_em_sal)

salery_max_theke_min_badh = high_sale-low_sale
print(salery_max_theke_min_badh)

574469
58966


# Pandas

# Ans to Q no 6 :

In [69]:

df = pd.read_csv("employees.csv")
df
print(df)
display(df.head(5))
df.info()
df.describe()

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR


id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

# Ans to Q no 7 :

In [70]:

df_d =pd.DataFrame(df,columns=['id','age','salary'])
display(df_d)
df_d.tail(3)

id  age  salary
0   1   56   77191
1   2   46   74131
2   3   32   46023
3   4   25   71090
4   5   38   31685
5   6   56   30769
6   7   36   89735
7   8   40   86101
8   9   28   32433
9  10   28   35311

id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

# Ans to Q no 8 :

In [71]:

it_em = df[df['dept']=='IT']
print(it_em)
total = len(it_em)
print(f"Total num of employee = {total}")

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
Total num of employee = 3


# Ans to Q no 9 :

In [72]:

sort_salary = df.sort_values('salary',ascending=False)
sort_salary
srt=sort_salary.head(3)
srt1 =pd.DataFrame(srt,columns=['age','salary','dept'])
print(display(srt1))

age  salary     dept
6   36   89735  Finance
7   40   86101       IT
0   56   77191       HR

None


# Ans to Q no 10 :

In [73]:

df.loc[df['salary']>80000,'salary']=80000
#df
display(df)
new_avg_sal = np.mean(df['salary'])
print(f"New avg value ={new_avg_sal}")

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   80000  Finance
7   8   40   80000       IT
8   9   28   32433    Sales
9  10   28   35311       HR

New avg value =55863.3
