<a href="https://colab.research.google.com/github/sonjoy1s/ML/blob/main/NUMPY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.random.randint(1,100, size =(10,5))
print(arr.shape)

(10, 5)


In [3]:
b = arr.reshape(5,10)
b.shape

(5, 10)

In [6]:
#covert to 1D
flatten = b.flatten()
print(flatten.ndim)

column_wise_flattening = np.ravel(b,order='c')
print(column_wise_flattening)

1
[47  4 48 22 30 62  9 68 92 71 83 55 65 56 27 42 51 79 75  8 13 36 93 73
 25 92 10 63 20 27 30 89 97 39 53 71 67  3 69 86 47 51 22 96  6 12 29 73
  8 68]


In [9]:
a = np.random.randint(1,100, size =(2,3))
b = np.random.randint(20,30, size =(2,3))


[[50 35 46]
 [19 93 45]] [[23 24 28]
 [26 22 29]]


In [11]:
# Concatenate
con_row = np.concatenate((a,b),axis=0) #row wise
print(con_row)
con_col = np.concatenate((a,b),axis=1) #col wise

print(con_col)

# amar jodi concetanate col korte jai 2 ta col er line same line value thaka lagbe and row er belay
# o ei ek oi kaj

[[50 35 46]
 [19 93 45]
 [23 24 28]
 [26 22 29]]
[[50 35 46 23 24 28]
 [19 93 45 26 22 29]]


In [15]:
# error
x = np.random.randint(1,10, size =(2,3))
y = np.random.randint(1,10, size =(1,3))
r =np.concatenate((x,y),axis=0)
print(r)

[[5 2 6]
 [3 1 8]
 [2 4 7]]


In [70]:
# Transpose matrix

#row ke col e neya
mat = np.array([[100,20,4],
                [30,40,200]])

tr = mat.T
print(tr)

[[100  30]
 [ 20  40]
 [  4 200]]


In [21]:
#array split
a = np.random.randint(1,10, size =(10,))
print(a)
splite_arr =np.array_split(a,3)
print(splite_arr)

[8 1 8 9 1 7 9 3 2 5]
[array([8, 1, 8, 9]), array([1, 7, 9]), array([3, 2, 5])]


In [29]:
# np arithmetic + math operation
x = np.array([10,8,30,100])
y = np.array([2,3,4,5])

add = x + y
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

rem = x % y
print(rem)

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [36]:
# math function
x = np.array([10,8,16,100])
base_10_log_val = np.log10(x)
print(base_10_log_val)

tow_log_diye_vag = np.log2(x)
print(tow_log_diye_vag)

sqrt = np.sqrt(x)
print(sqrt)

[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [40]:
#sum ber kora
s =np.sum(x)
print(s)

cumul =np.cumsum(x) # Changed cumulative_sum to cumsum
print(cumul)

134
[ 10  18  34 134]


In [43]:
# broadcasting
x = np.array([10,8,16,100]) #eitar sob ghula value sqrt korbo
print(x)
result = x**2
print(result)
rlt = x + 2
print(rlt)

[ 10   8  16 100]
[  100    64   256 10000]
[ 12  10  18 102]


In [44]:
mat = np.array([[10,20,30],
                [30,40,50]])
vector = np.array([1,2,3])
rlt = mat + vector
print(rlt)

[[11 22 33]
 [31 42 53]]


###logical Function

In [48]:
x = np.array([10,20,30,40])
y = np.array([2,3,30,5])

gr = x>y
print(gr)
eq = x == y
print(eq)



print(np.all(gr))
print(np.any(eq))

[ True  True False  True]
[False False  True False]
False
True


In [53]:
# sorting array

#inplace
x = np.array([10,3,30,5])
z = x.copy()
print(z)
z.sort()
print(z)

[10  3 30  5]
[ 3  5 10 30]
[10  3 30  5]


In [52]:
# copy sort
print(x)
sort_arr = np.sort(x)
print(sort_arr)

print(x)

[10  3 30  5]
[ 3  5 10 30]
[10  3 30  5]


In [55]:
# 2D sorting
x = np.array([[10,3,30,5],[9,4,6,2]])
hor_sort = np.sort(x,axis=1)
print(hor_sort)

br_sort = np.sort(x,axis=0)
print(br_sort)


[[ 3  5 10 30]
 [ 2  4  6  9]]
[[ 9  3  6  2]
 [10  4 30  5]]


In [56]:
# searching
print(x)


[[10  3 30  5]
 [ 9  4  6  2]]


In [61]:
#np.where
x =np.array([10,3,4,2,8])
index = np.where(x==3)
print(index)

index = np.where(x>3,x,0)
print(index)

(array([1]),)
[10  0  4  0  8]


In [71]:
print(mat)

index = np.where(mat>3)
print(index)

index = np.where(mat<40,mat,0)
print(index)

[[100  20   4]
 [ 30  40 200]]
(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))
[[ 0 20  4]
 [30  0  0]]


In [72]:
max_val_in = np.argmax(mat)
print(max_val_in)
min_val_in = np.argmin(mat)
print(min_val_in)

5
2


In [74]:
# count
a = np.random.randint(1,100, size =(100,))
print(a)

[59 57 64 55 89 93 49  3 44 10 72 66 24 93 74  4 26 66 23 66 12 90  8 25
 55 54 42 73 83 22 43  9 41 57  8 65 67 17  5 92 94 56 84 25 74 77 91 44
 36 51 64  9 25 87 62 12 28 65 79 54 63 98 73 95 56 45 11 20 46 10 40 84
 32  2 40 92 70 92 69 97 68 19  6  8 60 41 42 79 26 37 62 40  5 68 86 61
 88 25  8 76]


In [81]:
value_gr_than_60 = np.count_nonzero(a==30)
print(value_gr_than_60)



30


In [85]:
unique_val,count = np.unique(a,return_counts=True)
print(unique_val)
print(count)

[ 2  3  4  5  6  8  9 10 11 12 17 19 20 22 23 24 25 26 28 32 36 37 40 41
 42 43 44 45 46 49 51 54 55 56 57 59 60 61 62 63 64 65 66 67 68 69 70 72
 73 74 76 77 79 83 84 86 87 88 89 90 91 92 93 94 95 97 98]
[1 1 1 2 1 4 2 2 1 2 1 1 1 1 1 1 4 2 1 1 1 1 3 2 2 1 2 1 1 1 1 2 2 2 2 1 1
 1 2 1 2 2 3 1 2 1 1 1 2 2 1 1 2 1 2 1 1 1 1 1 1 3 2 1 1 1 1]


###satatics math


In [92]:
# data_load
data = np.genfromtxt('/student_scores.csv',delimiter=',',skip_header=1)
print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [101]:
math_mark = data[::,:1]
print(math_mark.T)
max_math = np.max(math_mark)
print(max_math)

min_math = np.min(math_mark)
print(min_math)
avg = np.mean(math_mark)
print(avg)

median_math_mrk = np.median(math_mark)
print(median_math_mrk)


#standrad deviation

std_math_mark = np.std(math_mark)
print(std_math_mark)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [103]:
study_h = np.array([2,4,5,7,8])
exm_score = np.array([65,75,78,88,92])
data = np.array([study_h,exm_score])
correlation = np.corrcoef(data)
print(correlation)

[[1.         0.99859154]
 [0.99859154 1.        ]]


###Linear Algebra

In [107]:
A =np.array([[1,2,3],
             [4,5,6]
             ])
B = np.array([[7,8],
              [9,10],
              [11,12]   # a er col ar b er row same lenght howa lagbe
              ])
dot_product = np.dot(A,B)
print(dot_product)
print(np.trace(A))

[[ 58  64]
 [139 154]]
6


In [112]:
sq_mat =np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
          ])
det_of_s = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)
print(det_of_s)
print(rank_sq)

0.0
2
