<a href="https://colab.research.google.com/github/sonjoy1s/ML/blob/main/NumpY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#np.zeros() -> 0 diye array banai
import numpy as np
arr = np.zeros((4,4,3),dtype =np.int8)
print(arr)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [4]:
arr2 =np.zeros_like(arr)
print(arr2)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [7]:
arr = np.ones((3,4,3),dtype=np.int8)
print(arr)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [9]:
ar = np.ones_like(arr)
print(ar)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [11]:
arr = np.empty((3,4,3),dtype=np.int64)
print(arr)

[[[          685857247                   0     137322989355007]
  [6874026229271586162 3037799373450208626 3038276273901630049]
  [ 732243302562232171 7233184988100130383 8386668381597623397]
  [3328452638448447337 7310027691118653984 2913388507452240479]]

 [[7020302829339043187 7091318335612940404 7236833163134198318]
  [7308044090252144243 5921784253751714926 4715943301812088421]
  [7595150837424088935 7378713966362127983 7957694959389405797]
  [7957664966976020521 7309940527955839589 7310010034491978867]]

 [[    136341294639463     137322909814144     137322909814080]
  [    137322909814016     137322909813952     137322909813888]
  [    137322909813824     137322909813760     137322909813696]
  [    137322909813632     137322909813568     137322909813504]]]


In [12]:
arr2 = np.empty_like(arr)
print(arr2)

[[[4607182418800017408 4607182418800017408 4605380978949069210]
  [4607182418800017408 4607182418800017408 4606546616499682750]
  [4603826795548251156 4607182418800017408 4607147096449998816]
  [4605840169499310907 4602007694522293662 4607182418800017408]]

 [[4607147096449998816 4604462597848585814 4599040617120731923]
  [4607182418800017408 4607111774099980224 4603155670897897906]
  [4597645384294997534 4607182418800017408 4607076451749961632]
  [4599181906520806292 4595102175093658901 4607182418800017408]]

 [[4606193392999496828 4592011469467032090 4592576627067329564]
  [4607182418800017408 4604851143698790328                   0]
  [4594537017493361427 4607182418800017408 4602696480347656208]
  [                  0 4594537017493361427 4607182418800017408]]]


In [17]:
arr = np.full((4,3),np.inf)
print(arr)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [22]:
arr2 =np.full_like(arr,np.inf,dtype=np.float64)
print(arr2)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


###Random values


In [28]:
#random   np.random.rand() -> je kono value nite pare 0 theke 1 er moddhe
import numpy as np
arr = np.random.rand(2,3)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.95765989 0.3201492  0.86719745]
 [0.00924654 0.62395663 0.61436056]]
float64
(2, 3)
2
6


In [29]:
## np.random.randint() -> je kono value rang er moddhe value nibe purno sonkkha dibe .dibe na
arr = np.random.randint(1,10,(4,3)) # 1 theke 10 rang er moddhe value niye output dekhabe
print(arr)

[[7 6 2]
 [3 4 7]
 [7 7 2]
 [8 9 4]]


In [32]:
## np.randoom.uniform()-> nidito rang er doshomik(.) man dibe .
arr = np.random.uniform(50,100,(2,4))
print(arr)

print("next")

arr1 = np.random.uniform(50, 100, (3, 3, 4))
print(arr1)


[[88.36048834 59.07613653 85.87505028 94.11722225]
 [60.10089198 89.94273249 76.42565525 57.46846982]]
next
[[[99.27334948 61.95054416 65.14409911 65.89793639]
  [71.47552225 53.41126452 52.07724956 56.89350429]
  [89.55415665 98.66553658 81.65021289 93.4660908 ]]

 [[96.8939684  64.00068962 52.81857396 56.00747533]
  [95.40620928 53.40098483 86.38166416 83.52597955]
  [75.06869582 97.85298385 69.123287   96.25573782]]

 [[99.5916171  69.6431854  84.995272   92.04900861]
  [90.89596644 84.40908812 71.60770986 61.83937493]
  [53.20391489 86.83176122 79.0062712  51.55240243]]]


In [33]:
## np.arang()->  nidishto dhap er man make korar jonno
import numpy as np
arr = np.arange(1,10,1) # 1 theke shuru hiche 10 porjonto jbe 1 step kore
print(arr)

[1 2 3 4 5 6 7 8 9]


In [34]:
mat =arr.reshape(3,3) # ei khane 3 ta row ar 3 col hobe
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
#np.linspace()-> nidoshto sonkkhok soman duruto jonno man make
arr = np.linspace(0,4,6) # 0 theke 4 porjonto jabe er moddhe 6 ta man lagbe
print(arr)

[0.  0.8 1.6 2.4 3.2 4. ]


In [38]:
#np.logspace() ->

arr = np.logspace(0, 4, 6, base=2)
print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


###Diagonal and identity matrix

In [41]:
## Diagonal matrix -> np.diag()
import numpy as np
arr = np.diag([1,2,3])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)
2


In [44]:
## identity matrix

mat = np.eye(4, dtype=np.int8)
print(mat)


mat2 = np.eye(3,4) # 4 ta col value nibe 3 ta row nibe
print(mat2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [45]:

mat2 = np.eye(3,4,1) # 4 ta col value nibe 3 ta row nibe 1 mane ek gor upore boshbe jodi -1 ditam tahole ek gor niche boshto
print(mat2)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###Indexing and Slicing

In [51]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],
                 [4,5,6]])

arr2[0][1]=100 # ei khane 0 bujhanu hoiche je fast arraylist ar 1 ta holo index number
arr2[1][2]=30  # 1 ta holo 2nd arraylist 2 ta holo index
print(arr2)

[[  1 100   3]
 [  4   5  30]]


In [52]:
# 1D array slicing
arr = np.array([1,2,3,4,5])
arr1 = arr[1:4].copy() # arr list er value copy kore ekta rakha hoiche
arr1[2]=200
print(arr)
print(arr1)

[1 2 3 4 5]
[  2   3 200]


In [55]:
## 2D slicing
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

row_0 = arr2[0:1, ] # row index er 0 theke 1 ag porjonto neo
row_1 = arr2[1:, ]  # 1 index theke neo

print(row_0)
print(row_1)

[[1 2 3]]
[[4 5 6]]
